# DataSource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/bank_app
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JPA Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.aop.auto=true
spring.aop.proxy-target-class=true


server.port=8181